name: "Marc Ziani de Ferranti"
description: "Personal website and blog of Marc Ziani de Ferranti"

url: "http://localhost:4000"

# Outputting
permalink: "/:categories/:title/"

# Markdown Processing
markdown: kramdown

# Plugins
gems:
- jekyll-less
- jekyll-haml

# Handling Reading
exclude: ['rakefile.rb', 'Guardfile', 'Gemfile', 'Gemfile.lock', 's3_website.yml']
