name: "Marc Ziani de Ferranti"
description: "Personal website and blog of Marc Ziani de Ferranti"

url: "http://localhost:4000"

# paginate: 10

# auto: true

# markdown: redcarpet
markdown: kramdown
permalink: pretty

gems:
- jekyll-compass
- jekyll-haml

exclude: ['rakefile.rb', 'Guardfile', 'Gemfile', 'Gemfile.lock', 's3_website.yml']