name: "Marc Ziani de Ferranti"
description: "Personal website and blog of Marc Ziani de Ferranti"

url: "http://www.marcziani.com"

# Outputting
permalink: "/:categories/:title/"

# Markdown Processing
markdown: kramdown

# Plugins
gems:
- jekyll-haml

# Grunt handles images and assets.
exclude: [
  'rakefile.rb', 'Gemfile', 'Gemfile.lock', 'package.json', 's3_website.yml',
  'node_modules/',
  'assets/img', 'assets/js',
  '**.png', '**.jpg', '**.jpeg', '**.gif', '**webp', '**.svg', '**.ico'
]

