name: "Marc Ziani de Ferranti"
description: "Personal website and blog of Marc Ziani de Ferranti"

url: "http://www.marcziani.com"

# Outputting
permalink: "/:categories/:title/"

# Markdown Processing
markdown: kramdown

# Plugins
gems:
- jekyll-haml
- jekyll-less

less:
  entrypoint: "assets/screen.less"
  compress: true

# Handling Reading
exclude: ['rakefile.rb', 'Guardfile', 'Gemfile', 'Gemfile.lock', 's3_website.yml']
