name: "Marc Ziani de Ferranti"
description: "Personal website and blog of Marc Ziani de Ferranti"

url: "http://localhost:4000"

# paginate: 10

# auto: true

markdown: redcarpet
permalink: pretty

exclude: ['rakefile', 'Guardfile', 'Gemfile', 'Gemfile.lock']